#define LEFT1     (input1 & BUTTON_LEFT)
#define RIGHT1    (input1 & BUTTON_RIGHT)
#define UP1       (input1 & BUTTON_UP)
#define DOWN1     (input1 & BUTTON_DOWN)
#define BUTTON1_B (input1 & BUTTON_B)
#define BUTTON1_A (input1 & BUTTON_A)
#define BUTTON1_X (input1 & BUTTON_X)
#define BUTTON1_Y (input1 & BUTTON_Y)
#define BUTTON1_L (input1 & BUTTON_L)
#define BUTTON1_R (input1 & BUTTON_R)
#define START1    (input1 & BUTTON_START)
#define SELECT1   (input1 & BUTTON_SELECT)


#define LEFT2     (input2 & BUTTON_LEFT)
#define RIGHT2    (input2 & BUTTON_RIGHT)
#define UP2       (input2 & BUTTON_UP)
#define DOWN2     (input2 & BUTTON_DOWN)
#define BUTTON2_B (input2 & BUTTON_B)
#define BUTTON2_A (input2 & BUTTON_A)
#define BUTTON2_X (input2 & BUTTON_X)
#define BUTTON2_Y (input2 & BUTTON_Y)
#define BUTTON2_L (input2 & BUTTON_L)
#define BUTTON2_R (input2 & BUTTON_R)
#define START2    (input2 & BUTTON_START)
#define SELECT2   (input2 & BUTTON_SELECT)

#define MOUSE1_R   (input1 & MOUSE_RIGHT)
#define MOUSE1_L   (input1 & MOUSE_LEFT)
#define MOUSE1_SPD ((input1 & MOUSE_SPEED) >> 2)

#define MOUSE2_R   (input2 & MOUSE_RIGHT)
#define MOUSE2_L   (input2 & MOUSE_LEFT)
#define MOUSE2_SPD (((input2 & MOUSE_SPEED) >> 10) & 0xFF)